---
k8s_version: "1.32"                                  # Kubernetes version to be installed
timezone: "Europe/Paris"                            # Timezone to set on all nodes
k8s_cni: flannel                                      # calico, flannel
container_runtime: containerd                        # docker, cri-o, containerd 
pod_network_cidr: "10.244.0.0/16"                    # to modif to match subnet of proxmox
configure_firewalld: false                           # true / false (keep it false, k8s>1.19 have issues with firewalld)
# Docker proxy support
setup_proxy: false                                   # Set to true to configure proxy
proxy_server: "proxy.example.com:8080"               # Proxy server address and port
docker_proxy_exclude: "localhost,127.0.0.1"          # Adresses to exclude from proxy
cluster_endpoint: "localhost"                        # Potential endpoint for a load balancer when we have high availability (for now, it's the ip of master node)