- name: Clean Master node
  hosts: master_nodes
  become: true
  become_method: ansible.builtin.sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - k8snodes.yml
    - vault_become_pass.yml
  tasks:
    - name: Clean process
      block:
        - include_role:
            name: clean
            tasks_from: rescue_master.yml
      when: clean_master == "true"


- name: Clean Worker node
  hosts: worker_nodes
  become: true
  become_method: ansible.builtin.sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - k8snodes.yml
    - vault_become_pass.yml
  tasks:
    - name: Clean process
      block:
        - include_role:
            name: clean
            tasks_from: rescue_worker.yml
      when: clean_worker == "true"
