- name: Clean Worker node
  hosts: worker_nodes
  become: true
  become_method: ansible.builtin.sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - k8snodes.yml
  tasks:
    - name: Clean worker_node
      block:
        - include_role:
            name: spawn-worker-node
            tasks_from: rescue_worker.yml
