---
- name: Prepare Kubernetes Nodes for Cluster bootstrapping
  hosts: k8snodes
  become: true
  become_method: ansible.builtin.sudo
  # gather_facts: no
  vars:
    ansible_ssh_private_key_file: ~/.ssh/ansible
  vars_files:
    - k8snodes.yml
  roles:
    - spawn-k8s
