---
- name: Prepare Kubernetes Nodes for Cluster bootstrapping
  hosts: k8snodes
  become: true
  become_method: ansible.builtin.sudo
  # gather_facts: no
  vars:
    ansible_ssh_private_key_file: ~/.ssh/ansible
  vars_files:
    - k8snodes.yml
  roles:
    - spawn-k8s

- name: Prepare Master node (test / not high availability)
  hosts: k8smaster
  become: true
  become_method: ansible.builtin.sudo
  vars:
    ansible_ssh_private_key_file: ~/.ssh/ansible
  vars_files:
    - k8snodes.yml
  roles:
    - spawn-control-panel

# - name: Prepare Worker Node (test / not high availability)
#   hosts: k8snode01
#   become: true
#   become_method: ansible.builtin.sudo
#   vars:
#     ansible_ssh_private_key_file: ~/.ssh/ansible
#   vars_files:
#     - k8snodes.yml
#   roles:
#     - spawn-worker-node
