---
- name: Prepare microservices
  hosts: kingslanding
  become: true
  become_method: ansible.builtin.sudo
  vars_files:
    - k8snodes.yml
    - vault_become_pass.yml
    - dockerhub-image-pull-secret.yml
    - dockerhub-image-pull-secret-copy.yml
    - dockerhub-image-pull-secret-copy-2.yml
  roles:
    - spawn-ota