all:
  hosts:
    kingslanding:
      ansible_host: 10.10.35.10
      k8s_role: master
      ansible_user: tyrion
    winterfell:
      ansible_host: 10.10.35.20
      k8s_role: master
      ansible_user: tyrion
    castralroc:
      ansible_host: 10.10.35.30
      k8s_role: master
      ansible_user: tyrion
    dragonstone:
      ansible_host: 10.10.35.40
      k8s_role: worker
      ansible_user: tyrion
    harrenhall:
      ansible_host: 10.10.35.50
      k8s_role: worker
      ansible_user: tyrion
    pyke:
      ansible_host: 10.10.35.60
      k8s_role: worker
      ansible_user: tyrion
  children:
    k8snodes:
      hosts:
        kingslanding:
        winterfell:
        castralroc:
        dragonstone:
        harrenhall:
        pyke:
    master_nodes:
      hosts:
        kingslanding:
        winterfell:
        castralroc:
    worker_nodes:
      hosts:
        dragonstone:
        harrenhall:
        pyke:
