all:
  hosts:
    k8smaster:
      ansible_host: 10.10.35.100
      k8s_role: master
    k8snode01:
      ansible_host: 10.10.35.110
      k8s_role: worker
  children:
    k8snodes:
      hosts:
        k8smaster:
        k8snode01:
    master_nodes:
      hosts:
        k8smaster:
    worker_nodes:
      hosts:
        k8snode01:
