all:
  hosts:
    snowdin:
      ansible_host: 10.10.35.100
      k8s_role: master
      ansible_user: papyrus
#    hotland:
#      ansible_host: 10.10.35.10
#      k8s_role: master
#      ansible_user: papyrus
#    ruins:
#      ansible_host: 10.10.35.20
#      k8s_role: master
#      ansible_user: papyrus
    waterfall:
      ansible_host: 10.10.35.110
      k8s_role: worker
      ansible_user: papyrus
  children:
    k8snodes:
      hosts:
        snowdin:
#        hotland:
#        ruins:
        waterfall:
    master_nodes:
      hosts:
        snowdin:
#        hotland:
#        ruins:
    worker_nodes:
      hosts:
        waterfall:
