all:
  hosts:
    snowdin:
      ansible_host: 10.10.35.100
      k8s_role: master
    waterfall:
      ansible_host: 10.10.35.110
      k8s_role: worker
  children:
    k8snodes:
      hosts:
        snowdin:
        waterfall:
    master_nodes:
      hosts:
        snowdin:
    worker_nodes:
      hosts:
        waterfall:
