---
- name: Include clean master
  block:
    - include_role:
        name: spawn-control-panel
        tasks_from: rescue_master.yml
  delegate_to: "{{ groups['master_nodes'][0] }}"

- name: Clean up worker-spawn
  block:
    - name: Reset kubeadm
      become: true
      shell: kubeadm reset --cri-socket=unix:///var/run/containerd/containerd.sock -f
      register: reset_result

    - name: Remove Docker directory
      become: true
      file:
        path: /var/lib/docker
        state: absent
      register: docker_dir_result
      failed_when: docker_dir_result.failed

  rescue:
    - name: Handle cleanup failure
      debug:
        msg: "Cleanup failed. Please manually inspect and clean up the system."