---
- name: Clean up worker-spawn node (snowdin)
  block:
    - name: Stop kubelet service
      become: true
      systemd:
        name: kubelet
        state: stopped
        enabled: no

    - name: Reset kubeadm
      become: true
      shell: kubeadm reset --cri-socket=unix:///var/run/containerd/containerd.sock -f
      register: reset_result
      ignore_errors: true

    - name: Remove Kubernetes directories
      become: true
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/kubelet
        - /etc/kubernetes
        - /etc/cni/net.d
        - /var/lib/etcd
        - /var/lib/dockershim
        - /var/run/kubernetes
        - /var/lib/cni

    - name: Remove containerd state
      become: true
      file:
        path: /var/lib/containerd
        state: absent

    - name: Remove Docker directory (if used)
      become: true
      file:
        path: /var/lib/docker
        state: absent
      register: docker_dir_result
      failed_when: docker_dir_result.failed and "'Could not find or access '/var/lib/docker'' not in docker_dir_result.msg"
      ignore_errors: true

    - name: Remove iptables rules
      become: true
      shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
      ignore_errors: true

    - name: Remove IP forwarding settings
      become: true
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '0'
        state: absent
      ignore_errors: true

    - name: Restart containerd
      become: true
      systemd:
        name: containerd
        state: restarted
  rescue:
    - name: Handle cleanup failure
      debug:
        msg: "Cleanup failed. Please manually inspect and clean up the system on node snowdin."

- name: Reboot node (snowdin)
  become: true
  reboot:
    reboot_timeout: 600

- name: Wait for node (snowdin) to come back online
  wait_for_connection:
    delay: 60
    timeout: 300