---
- name: Ensure target namespaces exist
  kubernetes.core.k8s:
    state: present
    kind: Namespace
    name: "{{ item }}"
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  loop: "{{ target_namespaces }}"

- name: Apply Docker Hub secret to target namespaces
  kubernetes.core.k8s:
    state: present
    definition: "{{ dockerhub-image-pull-secret | from_yaml }}"
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  loop: "{{ target_namespaces }}"
  loop_control:
    loop_var: item

- name: Patch default ServiceAccount in each target namespace to use the secret
  kubernetes.core.k8s:
    state: present
    kind: ServiceAccount
    name: default
    namespace: "{{ item }}"
    definition:
      imagePullSecrets:
        - name: "{{ secret_name }}"
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  loop: "{{ target_namespaces }}"
  loop_control:
    loop_var: item