- name: Setup Control Panel
  block:
    - name: create join_message.sh file
      file:
        path: "/home/papyrus/join_message.sh"
        state: touch
    
    - name: Initialize kubeadm
      become: true
      shell: kubeadm init --config /tmp/kubeadm/kubeadm-config.yml >>  /home/papyrus/join_message.sh
      register: join_message

    - name: create kube directory
      file:
        path:  $HOME/.kube
        state: directory
        owner: root

    - name: copy admin.conf to .kube/config
      become: true
      shell: cat  /etc/kubernetes/admin.conf > $HOME/.kube/config

    - name: Run cluster by regular user
      become: true
      shell: chown $(id -u):$(id -g) $HOME/.kube/config

#    - name: Ensure kubectl context uses the correct server address
#      shell: |
#        kubectl config set-cluster default --server=https://{{ ansible_host }}:6443 --kubeconfig=/home/papyrus/.kube/config
#        kubectl config set-context default --cluster=default --user=kubernetes-admin --namespace=default --kubeconfig=/home/papyrus/.kube/config
#        kubectl config use-context default --kubeconfig=/home/papyrus/.kube/config
#      delegate_to: "{{ inventory_hostname }}"


    - name: Wait for API server to be ready
      become: true
      shell: kubectl cluster-info --kubeconfig=$HOME/.kube/config
      register: cluster_info
      until: cluster_info.rc == 0
      retries: 5
      delay: 10

  
    - name: Set Up Pod Network
      become: true
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  rescue:
    - name: Error while set up master, rescue
      ansible.builtin.include_tasks: rescue_master.yml