- name: Initialize kubeadm
  become: true
  command: kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --cri-socket=unix:///var/run/cri-dockerd.sock

- name: create kube directory
  file:
    path: $HOME/.kube
    state: directory
    owner: root

- name: copy admin.conf to .kube/config
  shell: cat  /etc/kubernetes/admin.conf > $HOME/.kube/config

- name: Run cluster by regular user
  shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config


- name: Set Up Pod Network
  become: true
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 
