---
- name: Initialize kubeadm
  command: kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --control-plane-endpoint=cluster-endpoint --cri-socket=unix:///var/run/cri-dockerd.sock

- name: Create kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: '0755'

- name: Copy admin.conf to kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "root"
    group: "root"
    mode: '0644'
