- name: Setup Control Panel
  block:
    - name: Initialize kubeadm
      become: true
      shell: kubeadm init --config /tmp/kubeadm/kubeadm-config.yml
      register: join_message
     
    - name: Create kube home config folder
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        mode: "755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
  
    - name: copy admin.conf to .kube/config
      become: true
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        remote_src: true

    - name: Change owner of conf to user
      become: true
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube/config"
        state: file
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

#    - name: Ensure kubectl context uses the correct server address
#      shell: |
#        kubectl config set-cluster default --server=https://{{ ansible_host }}:6443 --kubeconfig=/home/papyrus/.kube/config
#        kubectl config set-context default --cluster=default --user=kubernetes-admin --namespace=default --kubeconfig=/home/papyrus/.kube/config
#        kubectl config use-context default --kubeconfig=/home/papyrus/.kube/config
#      delegate_to: "{{ inventory_hostname }}"


    - name: Wait for API server to be ready
      become: true
      shell: kubectl cluster-info --kubeconfig=/home/{{ ansible_user }}/.kube/config
      register: cluster_info
      until: cluster_info.rc == 0
      retries: 5
      delay: 20

  
    - name: Set Up Pod Network
      become: true
      shell: kubectl apply -f /tmp/kubeadm/kube-flannel.yml --kubeconfig=/home/{{ ansible_user }}/.kube/config
  rescue:
    - name: Error while set up master, rescue
      ansible.builtin.include_tasks: rescue_master.yml