- name: Setup Control Panel
  block:
    - name: Initialize kubeadm
      become: true
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16
      register: join_message
     
    - name: Create kube home config folder
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        mode: "755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
  
    - name: copy admin.conf to .kube/config
      become: true
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        remote_src: true

    - name: Change owner of conf to user
      become: true
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube/config"
        state: file
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Wait for API server to be ready
      become: true
      shell: kubectl cluster-info --kubeconfig=/home/{{ ansible_user }}/.kube/config # TODO: put env var 
      register: cluster_info
      until: cluster_info.rc == 0
      retries: 5
      delay: 20

  
#    - name: Set Up Pod Network (flannel)
#      become: true
#      shell: kubectl create -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml --kubeconfig=/home/{{ ansible_user }}/.kube/config # TODO: put env var 
#      register: flannel_install
    
    - name: Set Up Pod Network (calico new)
      become: true
      shell: kubectl create -f https://docs.projectcalico.org/manifests/calico.yaml --kubeconfig=/home/{{ ansible_user }}/.kube/config
      register: calico_install
      until: calico_install.rc == 0
      retries: 3
      delay: 10
#
#    - name: Set Up Calico Custom Resources
#      become: true
#      shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.2/manifests/custom-resources.yaml 
#      register: calico_2
#      until: calico_2.rc == 0
#      retries: 3
#      delay: 10
#
#    - name: Wait for Calico pods to be ready
#      become: true
#      shell: kubectl wait --for=condition=Ready pod -n calico-system --all --timeout=300s --kubeconfig=/home/{{ ansible_user }}/.kube/config
#      register: calico_ready
#      until: calico_ready.rc == 0
#      retries: 5
#      delay: 20
  
  rescue:
    - name: Error while set up master, rescue
      ansible.builtin.include_tasks: rescue_master.yml