---
- name: Begin spawn-master
  block: 
    - name: Include task to pre-setup for control panel
      ansible.builtin.include_tasks: pre_setup.yml

    - name: Include task to launch kubeadm
      ansible.builtin.include_tasks: kubeadm_init.yml
    
#    - name: Include task to authenticate on docker
#      ansible.builtin.include_tasks: auth_docker.yml
#
    - name: Include task to install cni 
      ansible.builtin.include_tasks: init_cni.yml
  rescue:
    - set_fact:
        clean_worker: "false"
    - ansible.builtin.include_role:
        name: clean
        tasks_from: rescue_master.yml

