---
basic_packages:
  - vim
  - bash-completion
  - wget
  - curl
  - apt-transport-https
  - ca-certificates
  - gnupg
  - software-properties-common
  - python3-pip
  - python3-kubernetes
  - python3-openshift
