
- name: Add Helm repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  loop:
    - { name: grafana, url: "https://grafana.github.io/helm-charts" }
    - { name: prometheus-community, url: "https://prometheus-community.github.io/helm-charts" }
    - { name: jetstack, url: "https://charts.jetstack.io" }

- name: Create monitoring namespace
  kubernetes.core.k8s:
    name: "monitoring"
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

- name: Create volume for prometheus/grafana
  kubernetes.core.k8s:
    state: present
    definition:
      kind: PersistentVolume
      apiVersion: v1
      metadata:
        name: "{{ item.name }}"
        labels:
          type: local
      spec:
        persistentVolumeReclaimPolicy: Retain
        storageClassName: local-storage
        capacity:
          storage: 15Gi
        accessModes:
          - ReadWriteOnce
        hostPath:
          path: "/home/{{ ansible_user }}/data/{{ item.name }}"
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  loop:
    - { name: "prometheus-pv-volume" }
    - { name: "grafana-pv-volume" }

- name: Create storage class
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-storage
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: kubernetes.io/no-provisioner
      volumeBindingMode: WaitForFirstConsumer
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

- name: Install kube-state-metrics
  kubernetes.core.helm:
    name: kube-state-metrics
    chart_ref: prometheus-community/kube-state-metrics
    release_namespace: "monitoring"
    create_namespace: false
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    values:
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi

- name: Install Prometheus
  kubernetes.core.helm:
    name:  prometheus
    chart_ref: prometheus
    chart_repo_url: https://prometheus-community.github.io/helm-charts
    release_namespace: "monitoring"
    create_namespace: false
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    values:
      alertmanager:
        enabled: false
      pushgateway:
        enabled: false
      server:
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
          runAsGroup: 0
          fsGroup: 0
        persistentVolume:
          enabled: true
          storageClass: local-storage
          size: 10Gi
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
      nodeExporter:
        enabled: true

- name: Install Loki
  kubernetes.core.helm:
    name: loki
    chart_ref: grafana
    release_namespace: "monitoring"
    chart_repo_url: https://grafana.github.io/helm-charts
    create_namespace: false
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    values:
      loki:
        auth_enabled: false
        storage:
          type: pvc
          pvc:
            size: 10Gi
      resources:
        limits:
          cpu: 300m
          memory: 768Mi
        requests:
          cpu: 100m
          memory: 256Mi
      persistence:
        storageClass: local-storage
        size: 10Gi

- name: Install Tempo
  kubernetes.core.helm:
    name: tempo
    chart_ref: grafana
    chart_repo_url: https://grafana.github.io/helm-charts
    release_namespace: "monitoring"
    create_namespace: false
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    values:
      tempo:
        search_enabled: true
      storage:
        pvc:
          size: 10Gi
      resources:
        limits:
          cpu: 300m
          memory: 768Mi
        requests:
          cpu: 100m
          memory: 256Mi

# Begin pre-setup for grafana
- name: Create ConfigMap for Grafana
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'dashboard-wireguard.yaml') }}"
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

- name: Create Grafana admin secret
  kubernetes.core.k8s:
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: grafana-admin-secret
        namespace: "monitoring"
      type: Opaque
      stringData:
        admin-user: "admin"
        admin-password: "cacaboudin" #to change

# Setting up stuff for database
- name: Create PV for postgres-grafana
  kubernetes.core.k8s:
    state: present
    definition:
      kind: PersistentVolume
      apiVersion: v1
      metadata:
        name: postgres-grafana-pv
        labels:
          name: local
      spec:
        persistentVolumeReclaimPolicy: Retain
        storageClassName: local-storage
        capacity:
          storage: 1Gi
        accessModes:
          - ReadWriteOnce
        hostPath:
          path: "/home/{{ ansible_user }}/data/postgres-grafana"
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

- name: Create PVC for postgres grafana
  kubernetes.core.k8s:
    state: present
    kubeconfig: "/home/{{ansible_user}}/.kube/config"
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: postgres-grafana-pvc
        namespace: monitoring
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        selector:
          matchLabels:
            name: local
        storageClassName: local-storage

- name: Create Deployment for postgres grafana
  kubernetes.core.k8s:
    state: present
    kubeconfig: "/home/{{ansible_user}}/.kube/config"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: postgres
        namespace: monitoring
        labels:
          app: postgres
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: postgres
        template:
          metadata:
            labels:
              app: postgres
          spec:
            containers:
            - name: postgres
              image: postgres:15
              ports:
              - containerPort: 5432
              env:
              - name: POSTGRES_USER
                value: "grafana"
              - name: POSTGRES_PASSWORD
                value: "{{ grafana_database_password }}"
              - name: POSTGRES_DB
                value: "grafana"
              volumeMounts:
              - name: postgres-data
                mountPath: /var/lib/postgresql/data
            volumes:
            - name: postgres-data
              persistentVolumeClaim:
                claimName: postgres-grafana-pvc

- name: Create Service for postgres grafana
  kubernetes.core.k8s:
    state: present
    kubeconfig: "/home/{{ansible_user}}/.kube/config"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: postgres-grafana-svc
        namespace: monitoring
      spec:
        selector:
          app: postgres
        ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
        type: ClusterIP

- name: Create Grafana database secret
  kubernetes.core.k8s:
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: grafana-db-credentials
        namespace: monitoring
      type: Opaque
      stringData:
        db-password: "{{ grafana_database_password }}"

- name: Install Grafana
  kubernetes.core.helm:
    name: grafana
    chart_ref: grafana
    chart_repo_url: https://grafana.github.io/helm-charts
    release_namespace: "monitoring"
    create_namespace: false
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    values:
      admin:
        existingSecret: grafana-admin-secret
        userKey: admin-user
        passwordKey: admin-password
      grafana.ini:
        database:
          type: postgres
          host: "postgres-grafana-svc.monitoring.svc.cluster.local:5432" 
          name: grafana
          user: grafana
          password: "{{ grafana_database_password }}" 
          ssl_mode: disable
      # Adding this to disable the security check
      assertNoLeakedSecrets: false
      dashboard:
        default:
          wireguard:
            file: /etc/config/wireguard.json
      persistence:
        enabled: "true"
        storageClass: local-storage
        size: 5Gi
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              uid: prometheus_uid
              type: prometheus
              url: http://prometheus-server.monitoring.svc.cluster.local:80
              access: proxy
            - name: Loki
              uid: loki_uid
              type: loki
              url: http://loki-grafana.monitoring.svc.cluster.local:80
              access: proxy
            - name: Tempo
              uid: tempo_uid
              type: tempo
              url: http://tempo-grafana.monitoring.svc.cluster.local:80
              access: proxy
      extraConfigmapMounts:
        - name: wireguard-configmap
          mountPath: /etc/config/wireguard.json
          configMap: wireguard-dashboard
          readOnly: true
      securityContext:
        runAsUser: 472
        runAsGroup: 472
        fsGroup: 472
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 512Mi

- name: Create grafana Ingress
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: grafana-ingress
        namespace: monitoring
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
          cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-production
          nginx.ingress.kubernetes.io/use-regex: "true"
      spec:
        ingressClassName: nginx
        tls:
          - hosts:
              - charizhard-grafana.duckdns.org
            secretName: grafana-tls-production
        rules:
          - host: charizhard-grafana.duckdns.org
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: grafana
                      port:
                        name: service
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

- name: Verify Prometheus installation
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: monitoring
    label_selectors:
      - app=prometheus
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  register: prometheus_pods

- name: Verify Loki installation
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: monitoring
    label_selectors:
      - app=loki
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  register: loki_pods

- name: Verify Tempo installation
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: monitoring
    label_selectors:
      - app=tempo
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  register: tempo_pods

- name: Verify Grafana installation
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: monitoring
    label_selectors:
      - app=grafana
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  register: grafana_pods

- name: Print installation status
  debug:
    msg:
      - "Prometheus Pods: {{ prometheus_pods.resources | map(attribute='metadata.name') | list }}"
      - "Loki Pods: {{ loki_pods.resources | map(attribute='metadata.name') | list }}"
      - "Tempo Pods: {{ tempo_pods.resources | map(attribute='metadata.name') | list }}"
      - "Grafana Pods: {{ grafana_pods.resources | map(attribute='metadata.name') | list }}"
