---
- name: Create Kubernetes Deployment for charizhard-server
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: charizhard-server
        namespace: default
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: charizhard-server
        template:
          metadata:
            labels:
              app: charizhard-server
          spec:
            hostNetwork: true
            dnsPolicy: ClusterFirstWithHostNet
            containers:
            - name: charizhard-server
              image: asthafinito/charizhard-server
              env:
              - name: PRIVATE_KEY
                value: "{{ private_key }}"
              ports:
              - containerPort: 51820
                protocol: UDP
              - containerPort: 8080
                protocol: TCP
              securityContext:
                privileged: true
                capabilities:
                  add: ["MKNOD", "NET_ADMIN", "NET_RAW"]
              volumeMounts:
              - mountPath: /dev/net/tun
                name: tun-device
            volumes:
            - name: tun-device
              hostPath:
                path: /dev/net/tun
            resources:
              limits:
                cpu: 2
                memory: 512Mi
              requests:
                cpu: 500m
                memory: 256Mi
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

- name: Create service for charizhard-server
  kubernetes.core.k8s:
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: charizhard-server-service
        namespace: default
      spec:
        selector:
          app: charizhard-server
        ports:
        - protocol: UDP
          port: 51820
          targetPort: 51820
          name: wireguard
        - protocol: TCP
          port: 8080
          targetPort: 8080
          name: http
        type: LoadBalancer


- name: Create charizhard-server Ingress
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: ch-wg-ingress
        namespace: default
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
          cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-staging
          nginx.ingress.kubernetes.io/use-regex: "true"
      spec:
        ingressClassName: nginx
        tls:
          - hosts:
              - '*.charizhard-wg.duckdns.org'
              - charizhard-wg.duckdns.org
            secretName: wg-tls-staging
        rules:
          - host: '*.charizhard-wg.duckdns.org'
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: charizhard-server-service
                      port:
                        name: http
          - host: charizhard-wg.duckdns.org
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: charizhard-server-service
                      port:
                        name: http
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"