---
- name: Create namespace for Keycloak
  kubernetes.core.k8s:
    name: keycloak
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

- name: Create postgres for keycloak
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'example-postgres.yml') }}"
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

- name: Create database secret
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'keycloak-db-secret.yml') }}"
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

- name: Create Keycloak ConfigMap for realms
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: keycloak-config
        namespace: keycloak
      data:
        "charizhard-ota-realm.json": |-
          {{ lookup('file', 'kc-config/charizhard-ota-realm.json') | from_json | to_json }}
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

- name: Deploy Keycloak directly
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: keycloak
        namespace: keycloak
        labels:
          app: keycloak
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: keycloak
        template:
          metadata:
            labels:
              app: keycloak
          spec:
            containers:
              - name: keycloak
                image: quay.io/keycloak/keycloak:26.1.4
                args: ["start" ]
                env:
                  - name: KEYCLOAK_ADMIN
                    value: "admin"
                  - name: KEYCLOAK_ADMIN_PASSWORD
                    value: "admin"
                  - name: KC_PROXY_HEADERS
                    value: "xforwarded"
                  - name: KC_HTTP_ENABLED
                    value: "true"
                  - name: KC_HEALTH_ENABLED
                    value: "true"
                  - name: KC_HOSTNAME
                    value: "charizhard-keycloak.duckdns.org"
                ports:
                  - name: http
                    containerPort: 8080
                readinessProbe:
                  httpGet:
                    path: /health/ready
                    port: 9000
                volumeMounts:
                  - name: keycloak-config-volume
                    mountPath: /etc/keycloak
            volumes:
              - name: keycloak-config-volume
                configMap:
                  name: keycloak-config
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

- name: Create Keycloak Service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: keycloak-service
        namespace: keycloak
      spec:
        selector:
          app: keycloak
        ports:
          - name: http
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
        type: ClusterIP
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"


- name: Create Keycloak Ingress
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: keycloak-ingress
        namespace: keycloak
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
          cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-staging

      spec:
        tls:
          - hosts:
              - charizhard-keycloak.duckdns.org
            secretName: kc-tls-staging
        rules:
          - host: charizhard-keycloak.duckdns.org
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: keycloak-service
                      port:
                        name: http
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
