- name: Add minio chart repo
  kubernetes.core.helm_repository:
    name: minio-operator
    repo_url: "https://operator.min.io"
    state: present
    force_update: true

- name: Create namespace for MinIO
  kubernetes.core.k8s:
    name: minio-tenant
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "/home/papyrus/.kube/config"

- name: Deploy MinIO using Helm
  kubernetes.core.helm:
    name: "operator"
    chart_ref: minio-operator/operator
    release_namespace: "minio-tenant"
    state: present
    values:
      operator:
        replicaCount: 1
        image:
          registry: quay.io
          repository: minio/operator
          tag: v5.0.11
          pullPolicy: Always
      tenants:
        - name: minio-tenant
          namespace: "minio-tenant"
          pools:
            - servers: 1
              volumesPerServer: 4
              size: 10Gi
          buckets:
            - name: bin
          users:
            - accessKey: "{{ minio_access_key }}"
              secretKey: "{{ minio_secret_key }}"
              policy:
                Version: "2012-10-17"
                Statement:
                  - Effect: "Allow"
                    Action:
                      - "s3:*"
                    Resource:
                      - "arn:aws:s3:::bin"
                      - "arn:aws:s3:::bin/*"
    kubeconfig: "/home/papyrus/.kube/config"


# - name: Wait for MinIO pods to be ready
#   kubernetes.core.k8s_info:
#     kind: Pod
#     namespace: "minio-tenant"
#     label_selectors:
#       - "app=minio"
#     kubeconfig: "/home/papyrus/.kube/config"
#   register: pod_list
#   until: pod_list.resources | length > 0 and pod_list.resources | selectattr('status.phase', 'equal', 'Running') | list | length == pod_list.resources | length
#   retries: 30
#   delay: 10
# 
# - name: Get MinIO service information
#   kubernetes.core.k8s_info:
#     kind: Service
#     namespace: "minio-tenant"
#     name: "minio-tenant-console"  #changed here based on search result
#     kubeconfig: "/home/papyrus/.kube/config"
#   register: minio_console_service
# 
# - name: Display MinIO connection details
#   debug:
#     msg: |
#       MinIO deployed successfully!
# 
#       Object Storage Endpoint (internal): http://minio-operator-minio.minio.svc.cluster.local:9000 # this may be different, check services in the minio namespace
# 
#       MinIO Console Endpoint: http://{{ minio_console_service.resources[0].spec.clusterIP }}:{{ minio_console_service.resources[0].spec.ports[0].port }}
# 
#       Remember to configure Ingress or port-forwarding for external access to the console.
