---
- name: Add cert-manager repo 
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Create namespace for cert-manager
  kubernetes.core.k8s:
    name: cert-manager
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"


- name: Install/upgrade cert-manager via Helm
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: cert-manager
    chart_repo_url: https://charts.jetstack.io
    release_namespace: cert-manager
    create_namespace: true
    state: present
    values:
      installCRDs: true
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  
- name: Create Let's Encrypt Issuer production
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Issuer
      metadata:
        name: letsencrypt-prod
        namespace: default
      spec:
        acme:
          # The ACME server URL
          server: https://acme-v02.api.letsencrypt.org/directory
          # Email address used for ACME registration
          email: amorroni@protonmail.com
          # Name of a secret used to store the ACME account private key
          privateKeySecretRef:
            name: letsencrypt-prod
          solvers:
            - dns01:

    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

