---
#- name: Begin ota microservice full deployment
#
#  block:
  - name: Include task to setup stuff
    ansible.builtin.include_tasks: setup.yml
  
  - name: Include task to init minio
    ansible.builtin.include_tasks: init_minio.yml

  - name: Include task to create ota pod
    ansible.builtin.include_tasks: init_ota.yml
#  rescue:
#      - include_role:
#         name: spawn-worker-node
#         tasks_from: rescue_worker.yml
    
