---
- name: Include task to setup stuff
  ansible.builtin.include_tasks: setup.yml

- name: Include task to setup external load balancer
  ansible.builtin.include_tasks: setup_load_balancer.yml

- name: Include task to setup ingress-controller
  ansible.builtin.include_tasks: setup_ingress_controller.yml

- name: Include task to setup cert-manager
  ansible.builtin.include_tasks: init_cert_manager.yml

- name: Include task to init minio
  ansible.builtin.include_tasks: init_minio_2.yml

- name: Include task to init keycloak
  ansible.builtin.include_tasks: init_keycloak.yml

- name: Include task to create ota pod
  ansible.builtin.include_tasks: init_ota.yml

- name: Include task to create charizhard-server
  ansible.builtin.include_tasks: init_charizhard_server.yml

- name: Include task to create charizhard-otp
  ansible.builtin.include_tasks: init_otp.yml

#- name: Include task to create metrics
#  ansible.builtin.include_tasks: init_metrics.yml