---
- name: Include task to setup stuff
  ansible.builtin.include_tasks: setup.yml

- name: Include task to init minio
  ansible.builtin.include_tasks: init_minio_2.yml

- name: Include task to create ota pod
  ansible.builtin.include_tasks: init_ota.yml
