---
- name: Include task to setup stuff
  ansible.builtin.include_tasks: setup.yml

- name: Include task to init minio
  ansible.builtin.include_tasks: init_minio_2.yml

- name: Include task to init keycloak test
  ansible.builtin.include_tasks: test_keycloak.yml

# - name: Include task to init keycloak
#   ansible.builtin.include_tasks: init_keycloak.yml

- name: Include task to create ota pod
  ansible.builtin.include_tasks: init_ota.yml

- name: Include task to create charizhard-server
  ansible.builtin.include_tasks: init_charizhard_server.yml
