---
- name: Init nginx service
  shell: kubectl --kubeconfig=/home/{{ ansible_user }}/.kube/config expose deployment hello-world --type=LoadBalancer --name=my-service
# TODO: put env var 
- name: Get node IP and port
  shell: kubectl --kubeconfig=/home/{{ ansible_user }}/.kube/config  get services my-service
  register: node_port
# TODO: put env var 
- name: Get node IP
  shell: kubectl --kubeconfig=/home/{{ ansible_user }}/.kube/config describe services my-service
  register: node_ip
# TODO: put env var 