- name: Apply ingress-nginx (ta mere)
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/baremetal/deploy.yaml --kubeconfig=/home/{{ ansible_user }}/.kube/config
  failed_when: false

- name: Patch ingress-nginx service to LoadBalancer
  kubernetes.core.k8s:
    api_version: v1
    kind: Service
    name: ingress-nginx-controller
    namespace: ingress-nginx
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    resource_definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: ingress-nginx-controller
        namespace: ingress-nginx
      spec:
        type: LoadBalancer

- name: Wait for ingress controller to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: ingress-nginx-controller
    namespace: ingress-nginx
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  register: ingress_deployment
  until: ingress_deployment.resources[0].status.readyReplicas is defined and ingress_deployment.resources[0].status.readyReplicas > 0
  retries: 10
  delay: 30
