---
- name: Install MetalLB
  become: true
  shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml --kubeconfig=/home/{{ ansible_user }}/.kube/config
  register: metallb_install

- name: Wait additional time for webhook to initialize
  ansible.builtin.pause:
    seconds: 60

- name: Set IP pool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: first-pool
        namespace: metallb-system
      spec:
        addresses:
        - 10.10.35.100-10.10.35.120
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

- name: Set Layer 2 configuration
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: example
        namespace: metallb-system
      spec:
        ipAddressPools:
        - first-pool
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
