- name: Config ingress-nginx
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'setup-ingress-nginx.yml') }}"
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  register: ingress_config_result
  ignore_errors: true

- name: Check if webhook configuration exists
  kubernetes.core.k8s_info:
    api_version: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name: ingress-nginx-admission
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  register: webhook_config
  ignore_errors: true

- name: Delete webhook configuration if it exists
  kubernetes.core.k8s:
    state: absent
    api_version: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name: ingress-nginx-admission
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  when: webhook_config.resources | length > 0
  ignore_errors: true

- name: Restart the ingress-nginx controller deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ingress-nginx-controller
        namespace: ingress-nginx
      spec:
        template:
          metadata:
            annotations:
              kubectl.kubernetes.io/restartedAt: "{{ ansible_date_time.iso8601 }}"
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

- name: Wait for ingress controller pods to be terminated
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: ingress-nginx
    label_selectors:
      - app.kubernetes.io/component=controller
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  register: ingress_pods
  until: ingress_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length == 0 or 
         (ingress_pods.resources | length > 0 and ingress_pods.resources[0].metadata.creationTimestamp | regex_search(ansible_date_time.date))
  retries: 10
  delay: 10
  ignore_errors: true

- name: Wait for new ingress controller pods to be ready
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: ingress-nginx
    label_selectors:
      - app.kubernetes.io/component=controller
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  register: new_ingress_pods
  until: >
    new_ingress_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length > 0 and
    new_ingress_pods.resources | selectattr('status.containerStatuses', 'defined') | list | length > 0
  retries: 15
  delay: 20

- name: Wait additional time for webhook to initialize
  ansible.builtin.pause:
    seconds: 60
