apiVersion: v1
kind: Secret
metadata:
  name: example-tls-secret
  namespace: keycloak
type: Opaque
data:
  cert.pem: "{{ cert1.content }}"
  chain.pem: "{{ chain1.content }}"
  fullchain.pem: "{{ fullchain1.content }}"
  privkey.pem: "{{ privkey1.content }}"