---
- name: Init nginx Pod
  shell: kubectl --kubeconfig=/home/{{ ansible_user }}/.kube/config apply -f https://k8s.io/examples/service/load-balancer-example.yaml
  register: init_nginx
  until: init_nginx.rc == 0
  retries: 5
  delay: 20
# TODO: put env var 