---
- name: Init nginx service
  shell: kubectl expose pod nginx-pod --type=NodePort --port=80 --name=nginx-service

- name: Get node IP and port
  shell: kubectl get svc nginx-service -o jsonpath='{.spec.ports[0].nodePort}'
  register: node_port

- name: Get node IP
  shell: kubectl get nodes -o jsonpath='{.items[0].status.addresses[0].address}'
  register: node_ip

- name: Test nginx service accessibility
  uri:
    url: "http://{{ node_ip.stdout }}:{{ node_port.stdout }}"
    status_code: 200
  register: result
  failed_when: result.status != 200