---
- name: Init nginx service
  shell: kubectl --kubeconfig=/home/{{ ansible_user }}/.kube/config expose pod nginx-pod --type=NodePort --port=80 --name=nginx-service

- name: Get node IP and port
  shell: kubectl --kubeconfig=/home/{{ ansible_user }}/.kube/config get svc nginx-service -o jsonpath='{.spec.ports[0].nodePort}'
  register: node_port

- name: Get node IP
  shell: kubectl --kubeconfig=/home/{{ ansible_user }}/.kube/config get nodes -o jsonpath='{.items[0].status.addresses[0].address}'
  register: node_ip
