---
- name: Create CNI bin directory
  become: true
  file:
    path: /opt/cni/bin
    state: directory
    mode: '0755'

- name: Get CNI binaries archive
  shell: wget https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz

- name: Extract CNI binaries
  become: true
  shell: tar -xzvf cni-plugins-linux-amd64-v1.1.1.tgz -C /opt/cni/bin

- name: Set permissions
  become: true
  file:
    path: "/opt/bni/bin/"
    recurse: true
    mode: "0755"
