---
- name: Update iptable setting
  shell: |
    cat <<EOF > /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    EOF

- name: Update iptable setting
  shell: sysctl --system