---
- name: add port
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
    - 6443
    - 2379-2380
    - 10250
    - 10252
    - 10255
    - 10251
