---
- name: Add port
  become: true
  ansible.builtin.command: iptables -A INPUT -p tcp --dport {{ item }} -j ACCEPT
  with_items:
    - 6443
    - 2379
    - 2380
    - 10250
    - 10252
    - 10255
    - 10251
  changed_when: false
