---
- name: Create modules-load.d configuration file
  ansible.builtin.copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf
    mode: "0644"

- name: Load overlay and br_netfilter modules
  community.general.modprobe:
    name: "{{ item }}"
  loop:
    - overlay
    - br_netfilter

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    sysctl_set: true
    sysctl_file: /etc/sysctl.conf
  become: true

- name: Update iptable setting
  ansible.builtin.shell: |
    cat <<EOF > /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    EOF
- name: Update iptable setting
  ansible.builtin.command: sysctl -p /etc/sysctl.d/k8s.conf
  become: true
  changed_when: true
