---
- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  ansible.builtin.shell: |
    swapoff -a

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'

# - name: Desable SELINUX first step
#   become: true
#   shell: setenforce 0  && sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
