---
- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg
    state: present
  when: docker_installed.rc != 0

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    filename: docker
    state: present
  when: docker_installed.rc != 0

- name: Install Containerd
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - containerd.io

- name: Create containerd directories required
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    mode: "755"
  with_items:
    - /etc/containerd

# - name: Ensure /etc/containerd/config.toml exists
#   become: true
#   ansible.builtin.copy:
#     content: "{{ containerd_default_config.stdout }}"
#     dest: /etc/containerd/config.toml
#     owner: root
#     group: root
#     mode: "0644"

- name: Generate default containerd config if it doesn't exist
  shell: containerd config default | sudo tee /etc/containerd/config.toml > /dev/null
  register: config_created

- name: Set SystemdCgroup to true in containerd config
  become: true
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^(\s*SystemdCgroup\s*=\s*)false'
    line: '\1true'
    backrefs: yes

- name: Start and enable containerd service
  become: true
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true
    daemon_reload: true