- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg
    state: present
  when: docker_installed.rc != 0

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    filename: docker
    state: present
  when: docker_installed.rc != 0

- name: Install Containerd
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - containerd.io

- name: Create containerd directories required
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/containerd

- name: Configure containerd with SystemdCgroup
  block:
    - name: Generate default containerd config
      ansible.builtin.command: containerd config default
      register: containerd_default_config

    - name: Set SystemdCgroup to true in containerd config
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'
      when: containerd_default_config.stdout.find('SystemdCgroup = false') != -1

    - name: Test Set stuff in config containerd
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'sandbox_image = "registry.k8s.io/pause:3.8"'
        replace: 'sandbox_image = "registry.k8s.io/pause:3.10"'
      when: containerd_default_config.stdout.find('SystemdCgroup = false') != -1
    
    - name: Ensure /etc/containerd/config.toml exists
      ansible.builtin.copy:
        content: "{{ containerd_default_config.stdout }}"
        dest: /etc/containerd/config.toml
        owner: root
        group: root
        mode: '0644'
      when: not (lookup('file', '/etc/containerd/config.toml', errors='ignore') or "")


- name: Start and enable containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true
    daemon_reload: true

