apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus_uid
    access: proxy
    url: http://prometheus-server.monitoring.svc.cluster.local:9090
    isDefault: true
